local compute_meta = require("blink-cmp-npm.utils.compute_meta")

describe("compute_meta", function()
  it("should compute cursor metadata", function()
    local meta = compute_meta({ line = '  "name": "1.0.0",', cursor = { 100, 4 } })
    local line, name, pos_end_name, pos_second_quote, pos_third_quote, pos_fourth_quote, current_version, current_version_matcher, last_quote_present, find_version =
      unpack(meta)
    assert.are.equal('  "name": "1.0.0",', line)
    assert.are.equal("name", name)
    assert.are.equal(7, pos_end_name)
    assert.are.equal(8, pos_second_quote)
    assert.are.equal(11, pos_third_quote)
    assert.are.equal(17, pos_fourth_quote)
    assert.are.equal("1.0.0", current_version)
    assert.are.equal("", current_version_matcher)
    assert.is_true(last_quote_present)
    assert.is_false(find_version)
  end)
end)
